### ISSUE TITLE
moth LAMP

### ISSUE THREAD

**Issue by JonathanGrant** [gabeochoa/fraud-online#11]

**Comment by gabeochoa** [comment]
https://www.bustle.com/p/what-is-the-moth-lamp-meme-heres-why-you-keep-seeing-this-meme-on-social-media-12067028

**Comment by gabeochoa** [comment]
https://github.com/gabeochoa/fraud-online/commit/bdae38e38569b57b3e4ed082ae56c505f514c5e6

implemented
